# Nome do seu workflow.
name: Java CI com Maven

# Gatilho para iniciar o workflow.
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

# Trabalhos (jobs) a serem executados.
jobs:
  build-and-test:
    # Máquina virtual que vai rodar o código.
    runs-on: ubuntu-latest

    # Etapas (steps) do job.
    steps:
      # 1. Baixar o código do seu repositório.
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Configurar o ambiente Java com a versão 21 do JDK.
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Adiciona cache para as dependências do Maven, acelerando builds futuros.

      # 3. Rodar os testes unitários com o Maven.
      - name: Rodar testes com Maven
        run: mvn test